### ISSUE TITLE
Fix progress bar updates

### ISSUE THREAD

**Issue by tnt-linden-hutchinson** [TNT-Hoopsnake/judy#27]
The progress bar length is not aligned with the number of updates it receives.

This causes the progress bar to indicate the run has finished, before the run has actually finished.

This is confusing/misleading for the user, who would expect a progress bar to act like an actual progress bar.

**Comment by tnt-rahul-raghavan** [comment]
This no longer occurs as progress bar was revamped in #31 to use pipeline stages.
