### ISSUE TITLE
Fix evaluation of models that require an API key

### ISSUE THREAD

**Issue by tnt-linden-hutchinson** [TNT-Hoopsnake/judy#28]
Currently it is not possible to evaluate a model that requires an API key (the model config pydantic definition does not include an api key).

`api_key` should be added as an optional value in the `ModelConfig` pydantic class.

Some logic for including the api key will need to be implemented in `base_responder.py`, as the TGI completion library used by easyllm does not allow an api_key kwarg, however this is required for completion libraries like OpenAI.

**Comment by tnt-rahul-raghavan** [comment]
This is now possible, added in #31
